[package]
name = "brack-tokenizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
unicode-segmentation = "1.11"
serde = { version = "1.0.195", features = ["derive"] }
